name: Déploiement GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout du code
        uses: actions/checkout@v3
        
      - name: Configuration de GitHub Pages
        uses: actions/configure-pages@v3
        
      - name: Upload des fichiers
        uses: actions/upload-pages-artifact@v2
        with:
          path: '.'
          
      - name: Déploiement vers GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2